# Generated by Django 5.0.4 on 2024-04-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nEvent', models.CharField(max_length=100, verbose_name='Nombre Del Evento')),
                ('nDate', models.DateField(verbose_name='Fecha')),
                ('nTime', models.TimeField(verbose_name='Hora')),
                ('nLocation', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('nDescription', models.TextField(max_length=255, verbose_name='Descripción del Evento')),
                ('nImagen', models.ImageField(blank=True, null=True, upload_to='eventos', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Eventos de Seguridad',
                'verbose_name_plural': 'Evento de Seguridad',
            },
        ),
    ]
