# Generated by Django 5.0.4 on 2024-04-28 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgsv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reventos',
            table='events',
        ),
    ]
